name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Linter
        run: npm run lint

      - name: Build Application
        run: npm run build
        env:
          VITE_APP_VERSION: "4.7.0"

      # Optional Deployment: Feel free to uncomment and configure your target deployment provider below
      # Example 1: Deploy to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   if: github.event_name == 'push'
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: dist
      #     branch: gh-pages

      # Example 2: Deploy to Firebase Hosting
      # - name: Deploy to Firebase Hosting
      #   if: github.event_name == 'push'
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     projectId: hotel-damview
      #     channelId: live
